name: Bug Report
description: Report a bug in imgcrush
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `imgcrush ...`
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened.
  - type: input
    id: version
    attributes:
      label: imgcrush version
      placeholder: "1.0.0"
    validations:
      required: true
  - type: dropdown
    id: hardware
    attributes:
      label: Hardware
      options:
        - Apple Silicon (M1/M2/M3/M4)
        - Intel Mac
    validations:
      required: true
  - type: input
    id: macos
    attributes:
      label: macOS version
      placeholder: "14.5"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Run with `--verbose` and paste the output.
      render: shell
